#!/usr/bin/env python3
"""
⚡ ClusterPay CLI Command Line Interface
Run:
    clusterpay setup    -> Generate admin key, 2FA secret, QR code & .env file
    clusterpay serve    -> Start the gateway server
    clusterpay version  -> Show version and system info
"""
import os
import sys
import secrets
import argparse

def generate_secrets():
    """Generates 256-bit cryptographically secure credentials and ASCII QR code."""
    try:
        import pyotp
    except ImportError:
        print("[+] Installing pyotp ...")
        os.system(f"{sys.executable} -m pip install pyotp -q")
        import pyotp

    try:
        import qrcode
    except ImportError:
        print("[+] Installing qrcode ...")
        os.system(f"{sys.executable} -m pip install qrcode -q")
        import qrcode

    admin_key = secrets.token_urlsafe(40)
    totp_secret = pyotp.random_base32()
    mongo_root_pw = secrets.token_urlsafe(24)
    mongo_app_pw = secrets.token_urlsafe(24)

    totp = pyotp.TOTP(totp_secret)
    otp_uri = totp.provisioning_uri(
        name="admin@clusterpay",
        issuer_name="ClusterPay Admin"
    )

    print()
    print("=" * 64)
    print("   🔐  ClusterPay Security & 2FA Setup")
    print("=" * 64)
    print()
    print("  ✅  ADMIN_MASTER_KEY  (admin console login password):")
    print(f"      {admin_key}")
    print()
    print("  ✅  ADMIN_TOTP_SECRET  (2FA — add to authenticator app):")
    print(f"      {totp_secret}")
    print()
    print("  ✅  MONGO_ROOT_PASSWORD  (MongoDB root admin):")
    print(f"      {mongo_root_pw}")
    print()
    print("  ✅  MONGO_PASSWORD  (MongoDB app user for gateway):")
    print(f"      {mongo_app_pw}")
    print()
    print("  📱  Scan this QR code with Google Authenticator / Authy:")
    print()

    qr = qrcode.QRCode(border=1)
    qr.add_data(otp_uri)
    qr.make(fit=True)
    qr.print_ascii(invert=True)

    print()
    print("  🌐  Or manually add on https://2fa.live:")
    print(f"      Secret Key: {totp_secret}")
    print()
    print("=" * 64)
    print("  📋  Configuration Template:")
    print()
    print(f"      ADMIN_MASTER_KEY={admin_key}")
    print(f"      ADMIN_TOTP_SECRET={totp_secret}")
    print(f"      MONGO_ROOT_PASSWORD={mongo_root_pw}")
    print(f"      MONGO_PASSWORD={mongo_app_pw}")
    print("=" * 64)
    print()

    env_path = os.path.join(os.getcwd(), ".env")
    if os.path.exists(env_path):
        ans = input(f"  .env already exists. Append keys to {env_path}? [y/N]: ").strip().lower()
        if ans == 'y':
            with open(env_path, 'a') as f:
                f.write("\n# Generated by clusterpay setup\n")
                f.write(f"ADMIN_MASTER_KEY={admin_key}\n")
                f.write(f"ADMIN_TOTP_SECRET={totp_secret}\n")
                f.write(f"MONGO_ROOT_PASSWORD={mongo_root_pw}\n")
                f.write(f"MONGO_PASSWORD={mongo_app_pw}\n")
            print(f"  ✅ Appended credentials to {env_path}")
    else:
        ans = input(f"  Create .env file at {env_path}? [Y/n]: ").strip().lower()
        if ans != 'n':
            with open(env_path, 'w') as f:
                f.write("# ClusterPay Node Environment\n")
                f.write(f"HOST=0.0.0.0\n")
                f.write(f"PORT=8085\n")
                f.write(f"BASE_URL=https://pay.yourstore.com\n")
                f.write(f"ENVIRONMENT=production\n")
                f.write(f"ADMIN_MASTER_KEY={admin_key}\n")
                f.write(f"ADMIN_TOTP_SECRET={totp_secret}\n")
                f.write(f"MONGO_ROOT_PASSWORD={mongo_root_pw}\n")
                f.write(f"MONGO_PASSWORD={mongo_app_pw}\n")
                f.write(f"MONGO_URI=mongodb://cpay_user:{mongo_app_pw}@127.0.0.1:27017/clusterpay_db?authSource=clusterpay_db\n")
                f.write(f"MONGO_DB_NAME=clusterpay_db\n")
                f.write(f"RATE_LIMIT_PER_MINUTE=60\n")
            print(f"  ✅ Written new .env to {env_path}")

    print()
    print("  🚀 Next Step: Run 'clusterpay serve' or 'docker compose up -d'")
    print()

def main():
    parser = argparse.ArgumentParser(
        prog="clusterpay",
        description="ClusterPay CLI - Non-Custodial Cryptocurrency Payment Gateway Toolkit"
    )
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # Command: setup / init
    subparsers.add_parser("setup", help="Generate Admin Master Key, 2FA TOTP secret, QR code, and .env file")
    subparsers.add_parser("init", help="Alias for setup")

    # Command: version
    subparsers.add_parser("version", help="Print installed ClusterPay version")

    args = parser.parse_args()

    if args.command in ("setup", "init"):
        generate_secrets()
    elif args.command == "version":
        from . import __version__
        print(f"ClusterPay CLI & SDK v{__version__}")
    else:
        parser.print_help()

if __name__ == "__main__":
    main()
