#!/usr/bin/env python3
"""
ClusterPay First-Time Security Setup
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Run ONCE after git clone to generate all credentials.

Usage:
    python scripts/generate_secrets.py

Outputs:
    - ADMIN_MASTER_KEY      : admin console login password
    - ADMIN_TOTP_SECRET     : 32-char Base32 key for Google Authenticator / 2fa.live
    - MONGO_ROOT_PASSWORD   : MongoDB root password (for Docker)
    - MONGO_PASSWORD        : MongoDB app user password (for Gateway service)
    - QR code in terminal   : scan with any TOTP authenticator app
    - Writes to .env        : if you confirm
"""
import os
import sys
import secrets


def _ensure_deps():
    missing = []
    try:
        import pyotp  # noqa: F401
    except ImportError:
        missing.append("pyotp")
    try:
        import qrcode  # noqa: F401
    except ImportError:
        missing.append("qrcode")
    if missing:
        print(f"[+] Installing: {', '.join(missing)} ...")
        os.system(f"{sys.executable} -m pip install {' '.join(missing)} -q")


def main():
    _ensure_deps()

    import pyotp
    import qrcode as qrcode_lib

    # ── Generate all credentials ───────────────────────────────────────────
    admin_key     = secrets.token_urlsafe(40)   # ~264 bits
    totp_secret   = pyotp.random_base32()        # RFC 4648 Base32, 160 bits
    mongo_root_pw = secrets.token_urlsafe(24)    # MongoDB root admin
    mongo_app_pw  = secrets.token_urlsafe(24)    # MongoDB app user (least-privilege)

    totp    = pyotp.TOTP(totp_secret)
    otp_uri = totp.provisioning_uri(
        name="admin@clusterpay",
        issuer_name="ClusterPay Admin"
    )

    W = 64
    print()
    print("=" * W)
    print("   🔐  ClusterPay Security Setup")
    print("=" * W)
    print()
    print("  ✅  ADMIN_MASTER_KEY  (admin console login password):")
    print(f"      {admin_key}")
    print()
    print("  ✅  ADMIN_TOTP_SECRET  (2FA — add to authenticator app):")
    print(f"      {totp_secret}")
    print()
    print("  ✅  MONGO_ROOT_PASSWORD  (MongoDB root admin):")
    print(f"      {mongo_root_pw}")
    print()
    print("  ✅  MONGO_PASSWORD  (MongoDB app user for gateway):")
    print(f"      {mongo_app_pw}")
    print()
    print("  📱  Scan the QR code below with Google Authenticator:")
    print()

    qr = qrcode_lib.QRCode(border=1)
    qr.add_data(otp_uri)
    qr.make(fit=True)
    qr.print_ascii(invert=True)

    print()
    print("  🌐  Or add manually at https://2fa.live:")
    print(f"      Secret key: {totp_secret}")
    print()
    print("  📋  Full .env snippet — copy all lines:")
    print()
    print(f"      ADMIN_MASTER_KEY={admin_key}")
    print(f"      ADMIN_TOTP_SECRET={totp_secret}")
    print(f"      MONGO_ROOT_PASSWORD={mongo_root_pw}")
    print(f"      MONGO_PASSWORD={mongo_app_pw}")
    print()
    print("=" * W)
    print("  ⚠️   IMPORTANT: Save ALL keys in a password manager.")
    print("      ADMIN_MASTER_KEY + TOTP   → required to log in to /admin")
    print("      MONGO_ROOT_PASSWORD       → MongoDB root (keep offline)")
    print("      MONGO_PASSWORD            → used by docker-compose.yml")
    print("      This script will NOT show them again.")
    print("=" * W)
    print()

    # ── Offer to write .env ────────────────────────────────────────────────
    env_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        ".env"
    )

    if os.path.exists(env_path):
        ans = input(f"  .env already exists. Append all keys to {env_path}? [y/N]: ").strip().lower()
        if ans == "y":
            with open(env_path, "a") as f:
                f.write("\n# ── Generated by scripts/generate_secrets.py ──────────────\n")
                f.write(f"ADMIN_MASTER_KEY={admin_key}\n")
                f.write(f"ADMIN_TOTP_SECRET={totp_secret}\n")
                f.write(f"MONGO_ROOT_PASSWORD={mongo_root_pw}\n")
                f.write(f"MONGO_PASSWORD={mongo_app_pw}\n")
            print(f"  ✅  Appended to {env_path}")
        else:
            print("  ℹ️   Skipped — copy the snippet above into your .env manually.")
    else:
        ans = input(f"  Create {env_path} with all defaults? [Y/n]: ").strip().lower()
        if ans != "n":
            with open(env_path, "w") as f:
                f.write("# ClusterPay Environment Configuration\n")
                f.write("# Generated by: python scripts/generate_secrets.py\n")
                f.write("#\n")
                f.write("HOST=0.0.0.0\n")
                f.write("PORT=8085\n")
                f.write("BASE_URL=https://pay.yourstore.com\n")
                f.write("ENVIRONMENT=production\n")
                f.write("DEBUG=false\n")
                f.write("\n")
                f.write("# MongoDB credentials (used by docker-compose.yml)\n")
                f.write(f"MONGO_ROOT_PASSWORD={mongo_root_pw}\n")
                f.write(f"MONGO_PASSWORD={mongo_app_pw}\n")
                f.write("MONGO_URI=mongodb://cpay_user:${MONGO_PASSWORD}@clusterpay-mongo:27017/clusterpay_db?authSource=clusterpay_db\n")
                f.write("MONGO_DB_NAME=clusterpay_db\n")
                f.write("\n")
                f.write("# Admin Authentication (both required to access /admin)\n")
                f.write(f"ADMIN_MASTER_KEY={admin_key}\n")
                f.write(f"ADMIN_TOTP_SECRET={totp_secret}\n")
                f.write("\n")
                f.write("# Rate limiting\n")
                f.write("RATE_LIMIT_PER_MINUTE=60\n")
                f.write("# REDIS_URL=redis://localhost:6379   # Uncomment for multi-worker accuracy\n")
            print(f"  ✅  Written to {env_path}")
            print("     Next: docker compose up -d")

    print()


if __name__ == "__main__":
    main()
